// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveEnrollments = `-- name: CountActiveEnrollments :one
SELECT COUNT(*)::bigint
FROM enrollments
WHERE batch_id = $1 AND status != 'dropped'
`

func (q *Queries) CountActiveEnrollments(ctx context.Context, batchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEnrollments, batchID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countBatches = `-- name: CountBatches :one
SELECT COUNT(*)::bigint
FROM batches
WHERE
    ($1::text    IS NULL OR status    = $1) AND
    ($2::uuid IS NULL OR course_id = $2) AND
    (
        $3::text IS NULL OR
        batch_name ILIKE '%' || $3 || '%' OR
        batch_code ILIKE '%' || $3 || '%'
    )
`

type CountBatchesParams struct {
	Status   *string     `json:"status"`
	CourseID pgtype.UUID `json:"course_id"`
	Search   *string     `json:"search"`
}

func (q *Queries) CountBatches(ctx context.Context, arg CountBatchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBatches, arg.Status, arg.CourseID, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (
    id, course_id, instructor_user_id, created_by_user_id,
    batch_name, batch_code, academic_year
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, course_id, instructor_user_id, created_by_user_id, batch_name, batch_code, academic_year, status, created_at, updated_at
`

type CreateBatchParams struct {
	ID               uuid.UUID `json:"id"`
	CourseID         uuid.UUID `json:"course_id"`
	InstructorUserID uuid.UUID `json:"instructor_user_id"`
	CreatedByUserID  uuid.UUID `json:"created_by_user_id"`
	BatchName        string    `json:"batch_name"`
	BatchCode        string    `json:"batch_code"`
	AcademicYear     *string   `json:"academic_year"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.ID,
		arg.CourseID,
		arg.InstructorUserID,
		arg.CreatedByUserID,
		arg.BatchName,
		arg.BatchCode,
		arg.AcademicYear,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorUserID,
		&i.CreatedByUserID,
		&i.BatchName,
		&i.BatchCode,
		&i.AcademicYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBatch = `-- name: DeleteBatch :exec
DELETE FROM batches WHERE id = $1
`

func (q *Queries) DeleteBatch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBatch, id)
	return err
}

const existsActiveTeacher = `-- name: ExistsActiveTeacher :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE id = $1 AND role = 'teacher' AND status = 'active'
)
`

func (q *Queries) ExistsActiveTeacher(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsActiveTeacher, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, course_id, instructor_user_id, created_by_user_id, batch_name, batch_code, academic_year, status, created_at, updated_at, course_name, course_code, instructor_first_name, instructor_last_name, enrolled_count FROM batches_with_stats WHERE id = $1
`

func (q *Queries) GetBatchByID(ctx context.Context, id uuid.UUID) (BatchesWithStat, error) {
	row := q.db.QueryRow(ctx, getBatchByID, id)
	var i BatchesWithStat
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorUserID,
		&i.CreatedByUserID,
		&i.BatchName,
		&i.BatchCode,
		&i.AcademicYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseName,
		&i.CourseCode,
		&i.InstructorFirstName,
		&i.InstructorLastName,
		&i.EnrolledCount,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT id, course_id, instructor_user_id, created_by_user_id, batch_name, batch_code, academic_year, status, created_at, updated_at, course_name, course_code, instructor_first_name, instructor_last_name, enrolled_count FROM batches_with_stats
WHERE
    ($1::text    IS NULL OR status    = $1) AND
    ($2::uuid IS NULL OR course_id = $2) AND
    (
        $3::text IS NULL OR
        batch_name ILIKE '%' || $3 || '%' OR
        batch_code ILIKE '%' || $3 || '%'
    )
ORDER BY created_at DESC
LIMIT  $5
OFFSET $4
`

type ListBatchesParams struct {
	Status     *string     `json:"status"`
	CourseID   pgtype.UUID `json:"course_id"`
	Search     *string     `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]BatchesWithStat, error) {
	rows, err := q.db.Query(ctx, listBatches,
		arg.Status,
		arg.CourseID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchesWithStat
	for rows.Next() {
		var i BatchesWithStat
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.InstructorUserID,
			&i.CreatedByUserID,
			&i.BatchName,
			&i.BatchCode,
			&i.AcademicYear,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseName,
			&i.CourseCode,
			&i.InstructorFirstName,
			&i.InstructorLastName,
			&i.EnrolledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatch = `-- name: UpdateBatch :one
UPDATE batches SET
    instructor_user_id = COALESCE($1, instructor_user_id),
    batch_name         = COALESCE($2,         batch_name),
    batch_code         = COALESCE($3,         batch_code),
    academic_year      = COALESCE($4,      academic_year),
    updated_at         = NOW()
WHERE id = $5
RETURNING id, course_id, instructor_user_id, created_by_user_id, batch_name, batch_code, academic_year, status, created_at, updated_at
`

type UpdateBatchParams struct {
	InstructorUserID pgtype.UUID `json:"instructor_user_id"`
	BatchName        *string     `json:"batch_name"`
	BatchCode        *string     `json:"batch_code"`
	AcademicYear     *string     `json:"academic_year"`
	ID               uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateBatch(ctx context.Context, arg UpdateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, updateBatch,
		arg.InstructorUserID,
		arg.BatchName,
		arg.BatchCode,
		arg.AcademicYear,
		arg.ID,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorUserID,
		&i.CreatedByUserID,
		&i.BatchName,
		&i.BatchCode,
		&i.AcademicYear,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBatchStatus = `-- name: UpdateBatchStatus :one
UPDATE batches SET
    status     = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, status, updated_at
`

type UpdateBatchStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

type UpdateBatchStatusRow struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBatchStatus(ctx context.Context, arg UpdateBatchStatusParams) (UpdateBatchStatusRow, error) {
	row := q.db.QueryRow(ctx, updateBatchStatus, arg.Status, arg.ID)
	var i UpdateBatchStatusRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}
