// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCourse = `-- name: ArchiveCourse :one
UPDATE courses SET
  status     = 'archived',
  updated_at = NOW()
WHERE id = $1
RETURNING id, status, updated_at
`

type ArchiveCourseRow struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ArchiveCourse(ctx context.Context, id uuid.UUID) (ArchiveCourseRow, error) {
	row := q.db.QueryRow(ctx, archiveCourse, id)
	var i ArchiveCourseRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*)
FROM courses
WHERE
  ($1::text IS NULL OR status = $1) AND
  ($2::text  IS NULL OR level  = $2)  AND
  (
    $3::text IS NULL OR
    course_name ILIKE '%' || $3 || '%' OR
    course_code ILIKE '%' || $3 || '%'
  )
`

type CountCoursesParams struct {
	Status *string `json:"status"`
	Level  *string `json:"level"`
	Search *string `json:"search"`
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, arg.Status, arg.Level, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOngoingBatchesByCourse = `-- name: CountOngoingBatchesByCourse :one
SELECT COUNT(*)::bigint
FROM batches
WHERE course_id = $1 AND status = 'ongoing'
`

func (q *Queries) CountOngoingBatchesByCourse(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOngoingBatchesByCourse, courseID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, course_name, course_code, description, subject, level, duration_weeks, price, max_capacity)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING id, course_name, course_code, description, subject, level, duration_weeks, price, max_capacity, status, created_at, updated_at
`

type CreateCourseParams struct {
	ID            uuid.UUID      `json:"id"`
	CourseName    string         `json:"course_name"`
	CourseCode    string         `json:"course_code"`
	Description   *string        `json:"description"`
	Subject       *string        `json:"subject"`
	Level         *string        `json:"level"`
	DurationWeeks *int32         `json:"duration_weeks"`
	Price         pgtype.Numeric `json:"price"`
	MaxCapacity   *int32         `json:"max_capacity"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.CourseName,
		arg.CourseCode,
		arg.Description,
		arg.Subject,
		arg.Level,
		arg.DurationWeeks,
		arg.Price,
		arg.MaxCapacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CourseName,
		&i.CourseCode,
		&i.Description,
		&i.Subject,
		&i.Level,
		&i.DurationWeeks,
		&i.Price,
		&i.MaxCapacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT
  c.id, c.course_name, c.course_code, c.description, c.subject, c.level,
  c.duration_weeks, c.price, c.max_capacity, c.status, c.created_at, c.updated_at,
  COUNT(b.id)::bigint                                       AS batch_count,
  COUNT(b.id) FILTER (WHERE b.status = 'ongoing')::bigint   AS ongoing_batch_count,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM enrollments e
    WHERE e.course_id = c.id AND e.status != 'dropped'
  ), 0)                                                      AS enrolled_count
FROM courses c
LEFT JOIN batches b ON b.course_id = c.id
WHERE c.id = $1
GROUP BY
  c.id, c.course_name, c.course_code, c.description, c.subject,
  c.level, c.duration_weeks, c.price, c.max_capacity, c.status,
  c.created_at, c.updated_at
`

type GetCourseByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	CourseName        string             `json:"course_name"`
	CourseCode        string             `json:"course_code"`
	Description       *string            `json:"description"`
	Subject           *string            `json:"subject"`
	Level             *string            `json:"level"`
	DurationWeeks     *int32             `json:"duration_weeks"`
	Price             pgtype.Numeric     `json:"price"`
	MaxCapacity       *int32             `json:"max_capacity"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	BatchCount        int64              `json:"batch_count"`
	OngoingBatchCount int64              `json:"ongoing_batch_count"`
	EnrolledCount     interface{}        `json:"enrolled_count"`
}

func (q *Queries) GetCourseByID(ctx context.Context, id uuid.UUID) (GetCourseByIDRow, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i GetCourseByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseName,
		&i.CourseCode,
		&i.Description,
		&i.Subject,
		&i.Level,
		&i.DurationWeeks,
		&i.Price,
		&i.MaxCapacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchCount,
		&i.OngoingBatchCount,
		&i.EnrolledCount,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
  id, course_name, course_code, description, subject, level,
  duration_weeks, price, max_capacity, status, created_at, updated_at,
  batch_count, ongoing_batch_count, enrolled_count
FROM courses_with_stats
WHERE
  ($1::text IS NULL OR status = $1) AND
  ($2::text  IS NULL OR level  = $2)  AND
  (
    $3::text IS NULL OR
    course_name ILIKE '%' || $3 || '%' OR
    course_code ILIKE '%' || $3 || '%'
  )
ORDER BY created_at DESC
LIMIT  $5
OFFSET $4
`

type ListCoursesParams struct {
	Status     *string `json:"status"`
	Level      *string `json:"level"`
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]CoursesWithStat, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Status,
		arg.Level,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesWithStat
	for rows.Next() {
		var i CoursesWithStat
		if err := rows.Scan(
			&i.ID,
			&i.CourseName,
			&i.CourseCode,
			&i.Description,
			&i.Subject,
			&i.Level,
			&i.DurationWeeks,
			&i.Price,
			&i.MaxCapacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatchCount,
			&i.OngoingBatchCount,
			&i.EnrolledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses SET
  course_name    = COALESCE($1,    course_name),
  course_code    = COALESCE($2,    course_code),
  description    = COALESCE($3,    description),
  subject        = COALESCE($4,        subject),
  level          = COALESCE($5,          level),
  duration_weeks = COALESCE($6, duration_weeks),
  price          = COALESCE($7,          price),
  max_capacity   = COALESCE($8,   max_capacity),
  updated_at     = NOW()
WHERE id = $9
RETURNING id, course_name, course_code, description, subject, level, duration_weeks, price, max_capacity, status, created_at, updated_at
`

type UpdateCourseParams struct {
	CourseName    *string        `json:"course_name"`
	CourseCode    *string        `json:"course_code"`
	Description   *string        `json:"description"`
	Subject       *string        `json:"subject"`
	Level         *string        `json:"level"`
	DurationWeeks *int32         `json:"duration_weeks"`
	Price         pgtype.Numeric `json:"price"`
	MaxCapacity   *int32         `json:"max_capacity"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.CourseName,
		arg.CourseCode,
		arg.Description,
		arg.Subject,
		arg.Level,
		arg.DurationWeeks,
		arg.Price,
		arg.MaxCapacity,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CourseName,
		&i.CourseCode,
		&i.Description,
		&i.Subject,
		&i.Level,
		&i.DurationWeeks,
		&i.Price,
		&i.MaxCapacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
