// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEnrollments = `-- name: CountEnrollments :one
SELECT COUNT(*)::bigint
FROM enrollments e
WHERE
    ($1::uuid       IS NULL OR e.batch_id       = $1) AND
    ($2::uuid     IS NULL OR e.student_id     = $2) AND
    ($3::text         IS NULL OR e.status         = $3) AND
    ($4::text IS NULL OR e.payment_status = $4)
`

type CountEnrollmentsParams struct {
	BatchID       pgtype.UUID `json:"batch_id"`
	StudentID     pgtype.UUID `json:"student_id"`
	Status        *string     `json:"status"`
	PaymentStatus *string     `json:"payment_status"`
}

func (q *Queries) CountEnrollments(ctx context.Context, arg CountEnrollmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrollments,
		arg.BatchID,
		arg.StudentID,
		arg.Status,
		arg.PaymentStatus,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (id, student_id, batch_id, course_id)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, student_id, batch_id, course_id, enrollment_date, status, payment_status, final_grade, created_at, updated_at
`

type CreateEnrollmentParams struct {
	ID        uuid.UUID `json:"id"`
	StudentID uuid.UUID `json:"student_id"`
	BatchID   uuid.UUID `json:"batch_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.StudentID,
		arg.BatchID,
		arg.CourseID,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BatchID,
		&i.CourseID,
		&i.EnrollmentDate,
		&i.Status,
		&i.PaymentStatus,
		&i.FinalGrade,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchForEnrollment = `-- name: GetBatchForEnrollment :one
SELECT b.id, b.status, b.course_id, c.max_capacity
FROM batches b
JOIN courses c ON c.id = b.course_id
WHERE b.id = $1
`

type GetBatchForEnrollmentRow struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	CourseID    uuid.UUID `json:"course_id"`
	MaxCapacity *int32    `json:"max_capacity"`
}

func (q *Queries) GetBatchForEnrollment(ctx context.Context, batchID uuid.UUID) (GetBatchForEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getBatchForEnrollment, batchID)
	var i GetBatchForEnrollmentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CourseID,
		&i.MaxCapacity,
	)
	return i, err
}

const getEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT
    e.id, e.status, e.payment_status, e.final_grade,
    e.enrollment_date, e.created_at, e.updated_at,
    e.student_id,
    s.first_name AS student_first_name,
    s.last_name  AS student_last_name,
    s.email      AS student_email,
    e.batch_id,
    b.batch_name, b.batch_code,
    b.status     AS batch_status,
    e.course_id,
    c.course_name, c.course_code
FROM enrollments e
JOIN students s ON s.id = e.student_id
JOIN batches  b ON b.id = e.batch_id
JOIN courses  c ON c.id = e.course_id
WHERE e.id = $1
`

type GetEnrollmentByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	FinalGrade       *string            `json:"final_grade"`
	EnrollmentDate   pgtype.Date        `json:"enrollment_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	StudentID        uuid.UUID          `json:"student_id"`
	StudentFirstName string             `json:"student_first_name"`
	StudentLastName  string             `json:"student_last_name"`
	StudentEmail     string             `json:"student_email"`
	BatchID          uuid.UUID          `json:"batch_id"`
	BatchName        string             `json:"batch_name"`
	BatchCode        string             `json:"batch_code"`
	BatchStatus      string             `json:"batch_status"`
	CourseID         uuid.UUID          `json:"course_id"`
	CourseName       string             `json:"course_name"`
	CourseCode       string             `json:"course_code"`
}

func (q *Queries) GetEnrollmentByID(ctx context.Context, id uuid.UUID) (GetEnrollmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByID, id)
	var i GetEnrollmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PaymentStatus,
		&i.FinalGrade,
		&i.EnrollmentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentID,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.StudentEmail,
		&i.BatchID,
		&i.BatchName,
		&i.BatchCode,
		&i.BatchStatus,
		&i.CourseID,
		&i.CourseName,
		&i.CourseCode,
	)
	return i, err
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT
    e.id, e.status, e.payment_status, e.final_grade,
    e.enrollment_date, e.created_at, e.updated_at,
    e.student_id,
    s.first_name AS student_first_name,
    s.last_name  AS student_last_name,
    s.email      AS student_email,
    e.batch_id,
    b.batch_name, b.batch_code,
    b.status     AS batch_status,
    e.course_id,
    c.course_name, c.course_code
FROM enrollments e
JOIN students s ON s.id = e.student_id
JOIN batches  b ON b.id = e.batch_id
JOIN courses  c ON c.id = e.course_id
WHERE
    ($1::uuid      IS NULL OR e.batch_id       = $1) AND
    ($2::uuid    IS NULL OR e.student_id     = $2) AND
    ($3::text        IS NULL OR e.status         = $3) AND
    ($4::text IS NULL OR e.payment_status = $4)
ORDER BY e.created_at DESC
LIMIT  $6
OFFSET $5
`

type ListEnrollmentsParams struct {
	BatchID       pgtype.UUID `json:"batch_id"`
	StudentID     pgtype.UUID `json:"student_id"`
	Status        *string     `json:"status"`
	PaymentStatus *string     `json:"payment_status"`
	PageOffset    int32       `json:"page_offset"`
	PageSize      int32       `json:"page_size"`
}

type ListEnrollmentsRow struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	FinalGrade       *string            `json:"final_grade"`
	EnrollmentDate   pgtype.Date        `json:"enrollment_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	StudentID        uuid.UUID          `json:"student_id"`
	StudentFirstName string             `json:"student_first_name"`
	StudentLastName  string             `json:"student_last_name"`
	StudentEmail     string             `json:"student_email"`
	BatchID          uuid.UUID          `json:"batch_id"`
	BatchName        string             `json:"batch_name"`
	BatchCode        string             `json:"batch_code"`
	BatchStatus      string             `json:"batch_status"`
	CourseID         uuid.UUID          `json:"course_id"`
	CourseName       string             `json:"course_name"`
	CourseCode       string             `json:"course_code"`
}

func (q *Queries) ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollments,
		arg.BatchID,
		arg.StudentID,
		arg.Status,
		arg.PaymentStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsRow
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PaymentStatus,
			&i.FinalGrade,
			&i.EnrollmentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentID,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.StudentEmail,
			&i.BatchID,
			&i.BatchName,
			&i.BatchCode,
			&i.BatchStatus,
			&i.CourseID,
			&i.CourseName,
			&i.CourseCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollment = `-- name: UpdateEnrollment :one
UPDATE enrollments SET
    status         = COALESCE($1,         status),
    payment_status = COALESCE($2, payment_status),
    final_grade    = COALESCE($3,    final_grade),
    updated_at     = NOW()
WHERE id = $4
RETURNING id, student_id, batch_id, course_id, enrollment_date, status, payment_status, final_grade, created_at, updated_at
`

type UpdateEnrollmentParams struct {
	Status        *string   `json:"status"`
	PaymentStatus *string   `json:"payment_status"`
	FinalGrade    *string   `json:"final_grade"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollment,
		arg.Status,
		arg.PaymentStatus,
		arg.FinalGrade,
		arg.ID,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BatchID,
		&i.CourseID,
		&i.EnrollmentDate,
		&i.Status,
		&i.PaymentStatus,
		&i.FinalGrade,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
