// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Batch struct {
	ID               uuid.UUID          `json:"id"`
	CourseID         uuid.UUID          `json:"course_id"`
	InstructorUserID uuid.UUID          `json:"instructor_user_id"`
	CreatorUserID    uuid.UUID          `json:"creator_user_id"`
	BatchName        string             `json:"batch_name"`
	BatchCode        string             `json:"batch_code"`
	AcademicYear     *string            `json:"academic_year"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BatchesWithStat struct {
	ID                  uuid.UUID          `json:"id"`
	CourseID            uuid.UUID          `json:"course_id"`
	InstructorUserID    uuid.UUID          `json:"instructor_user_id"`
	CreatorUserID       uuid.UUID          `json:"creator_user_id"`
	BatchName           string             `json:"batch_name"`
	BatchCode           string             `json:"batch_code"`
	AcademicYear        *string            `json:"academic_year"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CourseName          string             `json:"course_name"`
	CourseCode          string             `json:"course_code"`
	InstructorFirstName string             `json:"instructor_first_name"`
	InstructorLastName  string             `json:"instructor_last_name"`
	EnrolledCount       int64              `json:"enrolled_count"`
	FirstClassDate      interface{}        `json:"first_class_date"`
	LastClassDate       interface{}        `json:"last_class_date"`
}

type Course struct {
	ID           uuid.UUID          `json:"id"`
	CourseName   string             `json:"course_name"`
	CourseCode   string             `json:"course_code"`
	Description  *string            `json:"description"`
	Subject      *string            `json:"subject"`
	Level        *string            `json:"level"`
	SessionCount int32              `json:"session_count"`
	Price        pgtype.Numeric     `json:"price"`
	MaxCapacity  *int32             `json:"max_capacity"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CoursesWithStat struct {
	ID                uuid.UUID          `json:"id"`
	CourseName        string             `json:"course_name"`
	CourseCode        string             `json:"course_code"`
	Description       *string            `json:"description"`
	Subject           *string            `json:"subject"`
	Level             *string            `json:"level"`
	SessionCount      *int32             `json:"session_count"`
	Price             pgtype.Numeric     `json:"price"`
	MaxCapacity       *int32             `json:"max_capacity"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	BatchCount        int64              `json:"batch_count"`
	OngoingBatchCount int64              `json:"ongoing_batch_count"`
	EnrolledCount     int64              `json:"enrolled_count"`
}

type Enrollment struct {
	ID             uuid.UUID          `json:"id"`
	StudentID      uuid.UUID          `json:"student_id"`
	BatchID        uuid.UUID          `json:"batch_id"`
	CourseID       uuid.UUID          `json:"course_id"`
	EnrollmentDate pgtype.Date        `json:"enrollment_date"`
	Status         string             `json:"status"`
	PaymentStatus  string             `json:"payment_status"`
	FinalGrade     *string            `json:"final_grade"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID            uuid.UUID          `json:"id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	EventType     string             `json:"event_type"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	Location      *string            `json:"location"`
	Audience      string             `json:"audience"`
	CreatorUserID uuid.UUID          `json:"creator_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Form struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	Status         string             `json:"status"`
	AllowAnonymous bool               `json:"allow_anonymous"`
	CreatorUserID  uuid.UUID          `json:"creator_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type FormAnswer struct {
	ID          uuid.UUID `json:"id"`
	ResponseID  uuid.UUID `json:"response_id"`
	QuestionID  uuid.UUID `json:"question_id"`
	AnswerText  *string   `json:"answer_text"`
	AnswerValue []byte    `json:"answer_value"`
}

type FormQuestion struct {
	ID           uuid.UUID `json:"id"`
	FormID       uuid.UUID `json:"form_id"`
	QuestionText string    `json:"question_text"`
	QuestionType string    `json:"question_type"`
	IsRequired   bool      `json:"is_required"`
	OrderIndex   int32     `json:"order_index"`
	Options      []byte    `json:"options"`
}

type FormResponse struct {
	ID           uuid.UUID          `json:"id"`
	FormID       uuid.UUID          `json:"form_id"`
	RespondentID uuid.UUID          `json:"respondent_id"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Respondent struct {
	ID        uuid.UUID          `json:"id"`
	StudentID pgtype.UUID        `json:"student_id"`
	Name      *string            `json:"name"`
	Email     *string            `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Schedule struct {
	ID               uuid.UUID          `json:"id"`
	BatchID          uuid.UUID          `json:"batch_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	InstructorUserID pgtype.UUID        `json:"instructor_user_id"`
	DayOfWeek        string             `json:"day_of_week"`
	StartTime        pgtype.Time        `json:"start_time"`
	EndTime          pgtype.Time        `json:"end_time"`
	Room             *string            `json:"room"`
	Recurrence       string             `json:"recurrence"`
	EffectiveFrom    pgtype.Date        `json:"effective_from"`
	EffectiveUntil   pgtype.Date        `json:"effective_until"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ScheduleOverride struct {
	ID                  uuid.UUID          `json:"id"`
	ScheduleID          uuid.UUID          `json:"schedule_id"`
	OriginalDate        pgtype.Date        `json:"original_date"`
	OverrideType        string             `json:"override_type"`
	NewDate             pgtype.Date        `json:"new_date"`
	NewStartTime        pgtype.Time        `json:"new_start_time"`
	NewEndTime          pgtype.Time        `json:"new_end_time"`
	NewRoom             *string            `json:"new_room"`
	NewInstructorUserID pgtype.UUID        `json:"new_instructor_user_id"`
	Reason              *string            `json:"reason"`
	CreatorUserID       uuid.UUID          `json:"creator_user_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Student struct {
	ID               uuid.UUID          `json:"id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            *string            `json:"phone"`
	DateOfBirth      pgtype.Date        `json:"date_of_birth"`
	Gender           *string            `json:"gender"`
	Address          *string            `json:"address"`
	ParentName       *string            `json:"parent_name"`
	ParentPhone      *string            `json:"parent_phone"`
	RegistrationDate pgtype.Date        `json:"registration_date"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Role           string             `json:"role"`
	Phone          *string            `json:"phone"`
	Status         string             `json:"status"`
	FailedAttempts int32              `json:"failed_attempts"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
