// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    id, batch_id, course_id, instructor_user_id,
    day_of_week, start_time, end_time, room,
    recurrence, effective_from, effective_until
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
RETURNING id, batch_id, course_id, instructor_user_id, day_of_week, start_time, end_time, room, recurrence, effective_from, effective_until, created_at, updated_at
`

type CreateScheduleParams struct {
	ID               uuid.UUID   `json:"id"`
	BatchID          uuid.UUID   `json:"batch_id"`
	CourseID         uuid.UUID   `json:"course_id"`
	InstructorUserID pgtype.UUID `json:"instructor_user_id"`
	DayOfWeek        string      `json:"day_of_week"`
	StartTime        pgtype.Time `json:"start_time"`
	EndTime          pgtype.Time `json:"end_time"`
	Room             *string     `json:"room"`
	Recurrence       string      `json:"recurrence"`
	EffectiveFrom    pgtype.Date `json:"effective_from"`
	EffectiveUntil   pgtype.Date `json:"effective_until"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.BatchID,
		arg.CourseID,
		arg.InstructorUserID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
		arg.Recurrence,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CourseID,
		&i.InstructorUserID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Room,
		&i.Recurrence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const deleteScheduleOverride = `-- name: DeleteScheduleOverride :exec
DELETE FROM schedule_overrides WHERE id = $1
`

func (q *Queries) DeleteScheduleOverride(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleOverride, id)
	return err
}

const getBatchForSchedule = `-- name: GetBatchForSchedule :one
SELECT id, course_id, instructor_user_id FROM batches WHERE id = $1
`

type GetBatchForScheduleRow struct {
	ID               uuid.UUID `json:"id"`
	CourseID         uuid.UUID `json:"course_id"`
	InstructorUserID uuid.UUID `json:"instructor_user_id"`
}

func (q *Queries) GetBatchForSchedule(ctx context.Context, id uuid.UUID) (GetBatchForScheduleRow, error) {
	row := q.db.QueryRow(ctx, getBatchForSchedule, id)
	var i GetBatchForScheduleRow
	err := row.Scan(&i.ID, &i.CourseID, &i.InstructorUserID)
	return i, err
}

const getCourseSessionCount = `-- name: GetCourseSessionCount :one
SELECT session_count FROM courses WHERE id = $1
`

func (q *Queries) GetCourseSessionCount(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCourseSessionCount, id)
	var session_count int32
	err := row.Scan(&session_count)
	return session_count, err
}

const getOverrideByID = `-- name: GetOverrideByID :one
SELECT
    o.id, o.schedule_id, o.original_date, o.override_type,
    o.new_date, o.new_start_time, o.new_end_time, o.new_room,
    o.new_instructor_user_id, o.reason, o.created_by_user_id, o.created_at,
    u.first_name AS new_instructor_first_name,
    u.last_name  AS new_instructor_last_name
FROM schedule_overrides o
LEFT JOIN users u ON u.id = o.new_instructor_user_id
WHERE o.id = $1
`

type GetOverrideByIDRow struct {
	ID                     uuid.UUID          `json:"id"`
	ScheduleID             uuid.UUID          `json:"schedule_id"`
	OriginalDate           pgtype.Date        `json:"original_date"`
	OverrideType           string             `json:"override_type"`
	NewDate                pgtype.Date        `json:"new_date"`
	NewStartTime           pgtype.Time        `json:"new_start_time"`
	NewEndTime             pgtype.Time        `json:"new_end_time"`
	NewRoom                *string            `json:"new_room"`
	NewInstructorUserID    pgtype.UUID        `json:"new_instructor_user_id"`
	Reason                 *string            `json:"reason"`
	CreatedByUserID        uuid.UUID          `json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	NewInstructorFirstName *string            `json:"new_instructor_first_name"`
	NewInstructorLastName  *string            `json:"new_instructor_last_name"`
}

func (q *Queries) GetOverrideByID(ctx context.Context, id uuid.UUID) (GetOverrideByIDRow, error) {
	row := q.db.QueryRow(ctx, getOverrideByID, id)
	var i GetOverrideByIDRow
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.OriginalDate,
		&i.OverrideType,
		&i.NewDate,
		&i.NewStartTime,
		&i.NewEndTime,
		&i.NewRoom,
		&i.NewInstructorUserID,
		&i.Reason,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.NewInstructorFirstName,
		&i.NewInstructorLastName,
	)
	return i, err
}

const getOverridesByScheduleIDs = `-- name: GetOverridesByScheduleIDs :many
SELECT
    o.id, o.schedule_id, o.original_date, o.override_type,
    o.new_date, o.new_start_time, o.new_end_time, o.new_room,
    o.new_instructor_user_id, o.reason, o.created_by_user_id, o.created_at,
    u.first_name AS new_instructor_first_name,
    u.last_name  AS new_instructor_last_name
FROM schedule_overrides o
LEFT JOIN users u ON u.id = o.new_instructor_user_id
WHERE o.schedule_id = ANY($1::uuid[])
  AND (
      o.original_date BETWEEN $2::date AND $3::date
      OR (
          o.override_type = 'reschedule'
          AND o.new_date BETWEEN $2::date AND $3::date
      )
  )
`

type GetOverridesByScheduleIDsParams struct {
	ScheduleIds []uuid.UUID `json:"schedule_ids"`
	WeekStart   pgtype.Date `json:"week_start"`
	WeekEnd     pgtype.Date `json:"week_end"`
}

type GetOverridesByScheduleIDsRow struct {
	ID                     uuid.UUID          `json:"id"`
	ScheduleID             uuid.UUID          `json:"schedule_id"`
	OriginalDate           pgtype.Date        `json:"original_date"`
	OverrideType           string             `json:"override_type"`
	NewDate                pgtype.Date        `json:"new_date"`
	NewStartTime           pgtype.Time        `json:"new_start_time"`
	NewEndTime             pgtype.Time        `json:"new_end_time"`
	NewRoom                *string            `json:"new_room"`
	NewInstructorUserID    pgtype.UUID        `json:"new_instructor_user_id"`
	Reason                 *string            `json:"reason"`
	CreatedByUserID        uuid.UUID          `json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	NewInstructorFirstName *string            `json:"new_instructor_first_name"`
	NewInstructorLastName  *string            `json:"new_instructor_last_name"`
}

func (q *Queries) GetOverridesByScheduleIDs(ctx context.Context, arg GetOverridesByScheduleIDsParams) ([]GetOverridesByScheduleIDsRow, error) {
	rows, err := q.db.Query(ctx, getOverridesByScheduleIDs, arg.ScheduleIds, arg.WeekStart, arg.WeekEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverridesByScheduleIDsRow
	for rows.Next() {
		var i GetOverridesByScheduleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.OriginalDate,
			&i.OverrideType,
			&i.NewDate,
			&i.NewStartTime,
			&i.NewEndTime,
			&i.NewRoom,
			&i.NewInstructorUserID,
			&i.Reason,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.NewInstructorFirstName,
			&i.NewInstructorLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, batch_id, course_id, instructor_user_id, day_of_week, start_time, end_time, room, recurrence, effective_from, effective_until, created_at, updated_at FROM schedules WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CourseID,
		&i.InstructorUserID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Room,
		&i.Recurrence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedulesByBatch = `-- name: ListSchedulesByBatch :many
SELECT id, batch_id, course_id, instructor_user_id, day_of_week, start_time, end_time, room, recurrence, effective_from, effective_until, created_at, updated_at FROM schedules
WHERE batch_id = $1
ORDER BY day_of_week, start_time
`

func (q *Queries) ListSchedulesByBatch(ctx context.Context, batchID uuid.UUID) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CourseID,
			&i.InstructorUserID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
			&i.Recurrence,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByBatchForCount = `-- name: ListSchedulesByBatchForCount :many
SELECT id, recurrence, day_of_week, effective_from, effective_until
FROM schedules
WHERE batch_id = $1
`

type ListSchedulesByBatchForCountRow struct {
	ID             uuid.UUID   `json:"id"`
	Recurrence     string      `json:"recurrence"`
	DayOfWeek      string      `json:"day_of_week"`
	EffectiveFrom  pgtype.Date `json:"effective_from"`
	EffectiveUntil pgtype.Date `json:"effective_until"`
}

func (q *Queries) ListSchedulesByBatchForCount(ctx context.Context, batchID uuid.UUID) ([]ListSchedulesByBatchForCountRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesByBatchForCount, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesByBatchForCountRow
	for rows.Next() {
		var i ListSchedulesByBatchForCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Recurrence,
			&i.DayOfWeek,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForWeek = `-- name: ListSchedulesForWeek :many
SELECT
    s.id,
    s.batch_id,
    s.course_id,
    s.instructor_user_id,
    s.day_of_week,
    s.start_time,
    s.end_time,
    s.room,
    s.recurrence,
    s.effective_from,
    s.effective_until,
    b.batch_name,
    b.batch_code,
    b.instructor_user_id                AS batch_instructor_id,
    ub.first_name                       AS batch_instructor_first_name,
    ub.last_name                        AS batch_instructor_last_name,
    us.first_name                       AS sched_instructor_first_name,
    us.last_name                        AS sched_instructor_last_name,
    c.course_name,
    c.course_code,
    c.level                             AS course_level
FROM schedules s
JOIN batches b  ON b.id  = s.batch_id
JOIN courses c  ON c.id  = s.course_id
JOIN users   ub ON ub.id = b.instructor_user_id
LEFT JOIN users us ON us.id = s.instructor_user_id
WHERE s.effective_from <= $1::date
  AND (s.effective_until IS NULL OR s.effective_until >= $2::date)
  AND ($3::uuid IS NULL OR s.course_id = $3)
  AND ($4::uuid  IS NULL OR s.batch_id  = $4)
  AND ($5::text     IS NULL OR c.level     = $5)
ORDER BY s.day_of_week, s.start_time
`

type ListSchedulesForWeekParams struct {
	WeekEnd   pgtype.Date `json:"week_end"`
	WeekStart pgtype.Date `json:"week_start"`
	CourseID  pgtype.UUID `json:"course_id"`
	BatchID   pgtype.UUID `json:"batch_id"`
	Level     *string     `json:"level"`
}

type ListSchedulesForWeekRow struct {
	ID                       uuid.UUID   `json:"id"`
	BatchID                  uuid.UUID   `json:"batch_id"`
	CourseID                 uuid.UUID   `json:"course_id"`
	InstructorUserID         pgtype.UUID `json:"instructor_user_id"`
	DayOfWeek                string      `json:"day_of_week"`
	StartTime                pgtype.Time `json:"start_time"`
	EndTime                  pgtype.Time `json:"end_time"`
	Room                     *string     `json:"room"`
	Recurrence               string      `json:"recurrence"`
	EffectiveFrom            pgtype.Date `json:"effective_from"`
	EffectiveUntil           pgtype.Date `json:"effective_until"`
	BatchName                string      `json:"batch_name"`
	BatchCode                string      `json:"batch_code"`
	BatchInstructorID        uuid.UUID   `json:"batch_instructor_id"`
	BatchInstructorFirstName string      `json:"batch_instructor_first_name"`
	BatchInstructorLastName  string      `json:"batch_instructor_last_name"`
	SchedInstructorFirstName *string     `json:"sched_instructor_first_name"`
	SchedInstructorLastName  *string     `json:"sched_instructor_last_name"`
	CourseName               string      `json:"course_name"`
	CourseCode               string      `json:"course_code"`
	CourseLevel              *string     `json:"course_level"`
}

func (q *Queries) ListSchedulesForWeek(ctx context.Context, arg ListSchedulesForWeekParams) ([]ListSchedulesForWeekRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesForWeek,
		arg.WeekEnd,
		arg.WeekStart,
		arg.CourseID,
		arg.BatchID,
		arg.Level,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesForWeekRow
	for rows.Next() {
		var i ListSchedulesForWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CourseID,
			&i.InstructorUserID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
			&i.Recurrence,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.BatchName,
			&i.BatchCode,
			&i.BatchInstructorID,
			&i.BatchInstructorFirstName,
			&i.BatchInstructorLastName,
			&i.SchedInstructorFirstName,
			&i.SchedInstructorLastName,
			&i.CourseName,
			&i.CourseCode,
			&i.CourseLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET
    instructor_user_id = $1,
    day_of_week        = $2,
    start_time         = $3,
    end_time           = $4,
    room               = $5,
    recurrence         = $6,
    effective_from     = $7,
    effective_until    = $8,
    updated_at         = NOW()
WHERE id = $9
RETURNING id, batch_id, course_id, instructor_user_id, day_of_week, start_time, end_time, room, recurrence, effective_from, effective_until, created_at, updated_at
`

type UpdateScheduleParams struct {
	InstructorUserID pgtype.UUID `json:"instructor_user_id"`
	DayOfWeek        string      `json:"day_of_week"`
	StartTime        pgtype.Time `json:"start_time"`
	EndTime          pgtype.Time `json:"end_time"`
	Room             *string     `json:"room"`
	Recurrence       string      `json:"recurrence"`
	EffectiveFrom    pgtype.Date `json:"effective_from"`
	EffectiveUntil   pgtype.Date `json:"effective_until"`
	ID               uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.InstructorUserID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
		arg.Recurrence,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.ID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CourseID,
		&i.InstructorUserID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Room,
		&i.Recurrence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduleOverride = `-- name: UpdateScheduleOverride :one
UPDATE schedule_overrides SET
    new_date               = $1,
    new_start_time         = $2,
    new_end_time           = $3,
    new_room               = $4,
    new_instructor_user_id = $5,
    reason                 = $6
WHERE id = $7
RETURNING id, schedule_id, original_date, override_type, new_date, new_start_time, new_end_time, new_room, new_instructor_user_id, reason, created_by_user_id, created_at
`

type UpdateScheduleOverrideParams struct {
	NewDate             pgtype.Date `json:"new_date"`
	NewStartTime        pgtype.Time `json:"new_start_time"`
	NewEndTime          pgtype.Time `json:"new_end_time"`
	NewRoom             *string     `json:"new_room"`
	NewInstructorUserID pgtype.UUID `json:"new_instructor_user_id"`
	Reason              *string     `json:"reason"`
	ID                  uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateScheduleOverride(ctx context.Context, arg UpdateScheduleOverrideParams) (ScheduleOverride, error) {
	row := q.db.QueryRow(ctx, updateScheduleOverride,
		arg.NewDate,
		arg.NewStartTime,
		arg.NewEndTime,
		arg.NewRoom,
		arg.NewInstructorUserID,
		arg.Reason,
		arg.ID,
	)
	var i ScheduleOverride
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.OriginalDate,
		&i.OverrideType,
		&i.NewDate,
		&i.NewStartTime,
		&i.NewEndTime,
		&i.NewRoom,
		&i.NewInstructorUserID,
		&i.Reason,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertScheduleOverride = `-- name: UpsertScheduleOverride :one
INSERT INTO schedule_overrides (
    id, schedule_id, original_date, override_type,
    new_date, new_start_time, new_end_time, new_room,
    new_instructor_user_id, reason, created_by_user_id
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
ON CONFLICT (schedule_id, original_date) DO UPDATE SET
    new_date               = EXCLUDED.new_date,
    new_start_time         = EXCLUDED.new_start_time,
    new_end_time           = EXCLUDED.new_end_time,
    new_room               = EXCLUDED.new_room,
    new_instructor_user_id = EXCLUDED.new_instructor_user_id,
    reason                 = EXCLUDED.reason,
    created_by_user_id     = EXCLUDED.created_by_user_id
RETURNING id, schedule_id, original_date, override_type, new_date, new_start_time, new_end_time, new_room, new_instructor_user_id, reason, created_by_user_id, created_at
`

type UpsertScheduleOverrideParams struct {
	ID                  uuid.UUID   `json:"id"`
	ScheduleID          uuid.UUID   `json:"schedule_id"`
	OriginalDate        pgtype.Date `json:"original_date"`
	OverrideType        string      `json:"override_type"`
	NewDate             pgtype.Date `json:"new_date"`
	NewStartTime        pgtype.Time `json:"new_start_time"`
	NewEndTime          pgtype.Time `json:"new_end_time"`
	NewRoom             *string     `json:"new_room"`
	NewInstructorUserID pgtype.UUID `json:"new_instructor_user_id"`
	Reason              *string     `json:"reason"`
	CreatedByUserID     uuid.UUID   `json:"created_by_user_id"`
}

func (q *Queries) UpsertScheduleOverride(ctx context.Context, arg UpsertScheduleOverrideParams) (ScheduleOverride, error) {
	row := q.db.QueryRow(ctx, upsertScheduleOverride,
		arg.ID,
		arg.ScheduleID,
		arg.OriginalDate,
		arg.OverrideType,
		arg.NewDate,
		arg.NewStartTime,
		arg.NewEndTime,
		arg.NewRoom,
		arg.NewInstructorUserID,
		arg.Reason,
		arg.CreatedByUserID,
	)
	var i ScheduleOverride
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.OriginalDate,
		&i.OverrideType,
		&i.NewDate,
		&i.NewStartTime,
		&i.NewEndTime,
		&i.NewRoom,
		&i.NewInstructorUserID,
		&i.Reason,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
