// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*)
FROM students
WHERE
  ($1::text IS NULL OR status = $1) AND
  ($2::text IS NULL OR (
    first_name ILIKE '%' || $2 || '%' OR
    last_name  ILIKE '%' || $2 || '%' OR
    email      ILIKE '%' || $2 || '%'
  ))
`

type CountStudentsParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
  id, first_name, last_name, email, phone, date_of_birth, gender,
  address, parent_name, parent_phone, registration_date
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  COALESCE($11, CURRENT_DATE)
)
RETURNING id, first_name, last_name, email, phone, date_of_birth, gender,
          address, parent_name, parent_phone, registration_date, status, created_at, updated_at
`

type CreateStudentParams struct {
	ID               uuid.UUID   `json:"id"`
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Email            string      `json:"email"`
	Phone            *string     `json:"phone"`
	DateOfBirth      pgtype.Date `json:"date_of_birth"`
	Gender           *string     `json:"gender"`
	Address          *string     `json:"address"`
	ParentName       *string     `json:"parent_name"`
	ParentPhone      *string     `json:"parent_phone"`
	RegistrationDate interface{} `json:"registration_date"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.RegistrationDate,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.RegistrationDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentBatchCodes = `-- name: GetStudentBatchCodes :many
SELECT e.student_id, b.batch_code
FROM enrollments e
JOIN batches b ON e.batch_id = b.id
WHERE e.student_id = ANY($1::uuid[])
  AND e.status != 'dropped'
ORDER BY e.student_id, b.batch_code
`

type GetStudentBatchCodesRow struct {
	StudentID uuid.UUID `json:"student_id"`
	BatchCode string    `json:"batch_code"`
}

func (q *Queries) GetStudentBatchCodes(ctx context.Context, studentIds []uuid.UUID) ([]GetStudentBatchCodesRow, error) {
	rows, err := q.db.Query(ctx, getStudentBatchCodes, studentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentBatchCodesRow
	for rows.Next() {
		var i GetStudentBatchCodesRow
		if err := rows.Scan(&i.StudentID, &i.BatchCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT id, first_name, last_name, email, phone, date_of_birth, gender,
       address, parent_name, parent_phone, registration_date, status, created_at, updated_at
FROM students
WHERE email = $1
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.RegistrationDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, first_name, last_name, email, phone, date_of_birth, gender,
       address, parent_name, parent_phone, registration_date, status, created_at, updated_at
FROM students
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.RegistrationDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentEnrollments = `-- name: GetStudentEnrollments :many
SELECT
  e.id, e.status, e.payment_status, e.enrollment_date,
  b.id    AS batch_id,   b.batch_name, b.batch_code, b.status AS batch_status,
  c.id    AS course_id,  c.course_name, c.course_code, c.level
FROM enrollments e
JOIN batches b ON e.batch_id = b.id
JOIN courses c  ON e.course_id = c.id
WHERE e.student_id = $1
ORDER BY e.created_at DESC
LIMIT 50
`

type GetStudentEnrollmentsRow struct {
	ID             uuid.UUID   `json:"id"`
	Status         string      `json:"status"`
	PaymentStatus  string      `json:"payment_status"`
	EnrollmentDate pgtype.Date `json:"enrollment_date"`
	BatchID        uuid.UUID   `json:"batch_id"`
	BatchName      string      `json:"batch_name"`
	BatchCode      string      `json:"batch_code"`
	BatchStatus    string      `json:"batch_status"`
	CourseID       uuid.UUID   `json:"course_id"`
	CourseName     string      `json:"course_name"`
	CourseCode     string      `json:"course_code"`
	Level          *string     `json:"level"`
}

func (q *Queries) GetStudentEnrollments(ctx context.Context, studentID uuid.UUID) ([]GetStudentEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, getStudentEnrollments, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentEnrollmentsRow
	for rows.Next() {
		var i GetStudentEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.PaymentStatus,
			&i.EnrollmentDate,
			&i.BatchID,
			&i.BatchName,
			&i.BatchCode,
			&i.BatchStatus,
			&i.CourseID,
			&i.CourseName,
			&i.CourseCode,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, first_name, last_name, email, phone, date_of_birth, gender,
       address, parent_name, parent_phone, registration_date, status, created_at, updated_at
FROM students
WHERE
  ($1::text IS NULL OR status = $1) AND
  ($2::text IS NULL OR (
    first_name ILIKE '%' || $2 || '%' OR
    last_name  ILIKE '%' || $2 || '%' OR
    email      ILIKE '%' || $2 || '%'
  ))
ORDER BY created_at DESC
LIMIT  $4
OFFSET $3
`

type ListStudentsParams struct {
	Status     *string `json:"status"`
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DateOfBirth,
			&i.Gender,
			&i.Address,
			&i.ParentName,
			&i.ParentPhone,
			&i.RegistrationDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET
  first_name    = COALESCE($1,    first_name),
  last_name     = COALESCE($2,     last_name),
  email         = COALESCE($3,         email),
  phone         = COALESCE($4,         phone),
  date_of_birth = COALESCE($5, date_of_birth),
  gender        = COALESCE($6,        gender),
  address       = COALESCE($7,       address),
  parent_name   = COALESCE($8,   parent_name),
  parent_phone  = COALESCE($9,  parent_phone),
  status        = COALESCE($10,        status),
  updated_at    = NOW()
WHERE id = $11
RETURNING id, first_name, last_name, email, phone, date_of_birth, gender,
          address, parent_name, parent_phone, registration_date, status, created_at, updated_at
`

type UpdateStudentParams struct {
	FirstName   *string     `json:"first_name"`
	LastName    *string     `json:"last_name"`
	Email       *string     `json:"email"`
	Phone       *string     `json:"phone"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      *string     `json:"gender"`
	Address     *string     `json:"address"`
	ParentName  *string     `json:"parent_name"`
	ParentPhone *string     `json:"parent_phone"`
	Status      *string     `json:"status"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.Status,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.RegistrationDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudentFull = `-- name: UpdateStudentFull :one
UPDATE students SET
  first_name    = $1,
  last_name     = $2,
  email         = $3,
  phone         = $4,
  date_of_birth = $5,
  gender        = $6,
  address       = $7,
  parent_name   = $8,
  parent_phone  = $9,
  status        = $10,
  updated_at    = NOW()
WHERE id = $11
RETURNING id, first_name, last_name, email, phone, date_of_birth, gender,
          address, parent_name, parent_phone, registration_date, status, created_at, updated_at
`

type UpdateStudentFullParams struct {
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Email       string      `json:"email"`
	Phone       *string     `json:"phone"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      *string     `json:"gender"`
	Address     *string     `json:"address"`
	ParentName  *string     `json:"parent_name"`
	ParentPhone *string     `json:"parent_phone"`
	Status      string      `json:"status"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateStudentFull(ctx context.Context, arg UpdateStudentFullParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudentFull,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.ParentName,
		arg.ParentPhone,
		arg.Status,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.ParentName,
		&i.ParentPhone,
		&i.RegistrationDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
