// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
WHERE
  ($1::text   IS NULL OR role   = $1)   AND
  ($2::text IS NULL OR status = $2)
`

type CountUsersParams struct {
	Role   *string `json:"role"`
	Status *string `json:"status"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Role, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, first_name, last_name, email, password_hash, role, phone)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, first_name, last_name, email, role, phone, status, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Phone        *string   `json:"phone"`
}

type CreateUserRow struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Phone     *string            `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Phone,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getUserByIDFull = `-- name: GetUserByIDFull :one
SELECT id, first_name, last_name, email, role, phone, status, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDFullRow struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Phone     *string            `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByIDFull(ctx context.Context, id uuid.UUID) (GetUserByIDFullRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDFull, id)
	var i GetUserByIDFullRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, email, role, phone, status, created_at, updated_at
FROM users
WHERE
  ($1::text   IS NULL OR role   = $1)   AND
  ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT  $4
OFFSET $3
`

type ListUsersParams struct {
	Role       *string `json:"role"`
	Status     *string `json:"status"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

type ListUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Phone     *string            `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Role,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  first_name = COALESCE($1, first_name),
  last_name  = COALESCE($2,  last_name),
  email      = COALESCE($3,      email),
  role       = COALESCE($4,       role),
  phone      = COALESCE($5,      phone),
  status     = COALESCE($6,     status),
  updated_at = NOW()
WHERE id = $7
RETURNING id, first_name, last_name, email, role, phone, status, created_at, updated_at
`

type UpdateUserParams struct {
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	Email     *string   `json:"email"`
	Role      *string   `json:"role"`
	Phone     *string   `json:"phone"`
	Status    *string   `json:"status"`
	ID        uuid.UUID `json:"id"`
}

type UpdateUserRow struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Phone     *string            `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
		arg.Phone,
		arg.Status,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
